name: my_pro9
description: "A new Flutter project."

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  google_fonts: ^6.1.0 
  qr_flutter: ^4.1.0
  hive: ^2.2.3
  hive_flutter: 1.1.0
  http: ^1.2.1
  provider: ^6.1.2
  cached_network_image: ^3.3.0
  # shared_preferences removed in favor of Hive for session storage




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/icons/  # Add trailing slash
    - assets/images/ # Add trailing slash
    # Or specify individual files:
    # - assets/icons/icon1.png
    # - assets/icons/icon2.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" 
  adaptive_icon_background: "#0E2A51"